### ISSUE TITLE
Jou can "join" a community that you have already joined

### ISSUE THREAD

**Issue by syrop** [syrop/Victor-Events#1]
When you seek a community that is already joined, and then join it, SQL constraints are violated:

2019-01-03 16:37:24.872 17621-17709/pl.org.seva.events E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: pl.org.seva.events, PID: 17621
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: communities.name (code 1555)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:788)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:926)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
        at pl.org.seva.events.comm.CommDao_Impl.insert(CommDao_Impl.java:76)
        at pl.org.seva.events.comm.Comms$join$1.invokeSuspend(Comms.kt:47)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by syrop** [comment]
Fixed.

**Comment by syrop** [comment]
No longer throws an exception, yet the list of joined communities is apparently not remembered when no user is logged in.

**Comment by syrop** [comment]
Reopened by mistake.
